name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'Twrp_Device_Genter'
      IMG_URL:
        description: 'IMG_URL'
        required: true
        default: 'https://github.com/Xpsoted/Action-Recovery-builder/releases/download/1404192362/recovery.img'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python python3 python-pip python3-pip cpio wget
      
    - name: Set variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var
      
    - name: Install TWRP generator 
      run: |
        pip3 install twrpdtgen
        mkdir dt
    
    - name: Download boot or recovery img
      run: |
        wget ${{ github.event.inputs.IMG_URL }}
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img
    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt
    - uses: actions/upload-artifact@v3
      with:
        name: gt2
        path: ./DeviceTree.zip
        if-no-files-found: ignore
      env:
        GITHUB_TOKEN: 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
